"""empty message

Revision ID: 648a82fe81c0
Revises: 6a21f9fff7ff
Create Date: 2023-08-24 21:02:53.728926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648a82fe81c0'
down_revision = '6a21f9fff7ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'is_active')
    # ### end Alembic commands ###
