"""empty message

Revision ID: 6a21f9fff7ff
Revises: 6c28c368f175
Create Date: 2023-08-24 20:05:35.803439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a21f9fff7ff'
down_revision = '6c28c368f175'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_local', sa.Integer(), nullable=True),
    sa.Column('team_visitor', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('score_local', sa.Integer(), nullable=True),
    sa.Column('score_visitor', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('loser', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Boolean(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('referee_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_match_date'), 'match', ['date'], unique=False)
    op.create_index(op.f('ix_match_loser'), 'match', ['loser'], unique=False)
    op.create_index(op.f('ix_match_match_id'), 'match', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_referee_id'), 'match', ['referee_id'], unique=False)
    op.create_index(op.f('ix_match_score_local'), 'match', ['score_local'], unique=False)
    op.create_index(op.f('ix_match_score_visitor'), 'match', ['score_visitor'], unique=False)
    op.create_index(op.f('ix_match_stadium_id'), 'match', ['stadium_id'], unique=False)
    op.create_index(op.f('ix_match_team_local'), 'match', ['team_local'], unique=False)
    op.create_index(op.f('ix_match_team_visitor'), 'match', ['team_visitor'], unique=False)
    op.create_index(op.f('ix_match_tournament_id'), 'match', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_match_winner'), 'match', ['winner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_winner'), table_name='match')
    op.drop_index(op.f('ix_match_tournament_id'), table_name='match')
    op.drop_index(op.f('ix_match_team_visitor'), table_name='match')
    op.drop_index(op.f('ix_match_team_local'), table_name='match')
    op.drop_index(op.f('ix_match_stadium_id'), table_name='match')
    op.drop_index(op.f('ix_match_score_visitor'), table_name='match')
    op.drop_index(op.f('ix_match_score_local'), table_name='match')
    op.drop_index(op.f('ix_match_referee_id'), table_name='match')
    op.drop_index(op.f('ix_match_match_id'), table_name='match')
    op.drop_index(op.f('ix_match_loser'), table_name='match')
    op.drop_index(op.f('ix_match_date'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
