"""empty message

Revision ID: 6c28c368f175
Revises: 3dc81cd525ce
Create Date: 2023-08-21 18:29:26.759387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c28c368f175'
down_revision = '3dc81cd525ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('foundation_date', sa.Date(), nullable=True))
    op.add_column('team', sa.Column('logo', sa.String(), nullable=True))
    op.create_index(op.f('ix_team_foundation_date'), 'team', ['foundation_date'], unique=False)
    op.create_index(op.f('ix_team_logo'), 'team', ['logo'], unique=False)
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_role_id'), 'user', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_id'), table_name='user')
    op.drop_column('user', 'role_id')
    op.drop_index(op.f('ix_team_logo'), table_name='team')
    op.drop_index(op.f('ix_team_foundation_date'), table_name='team')
    op.drop_column('team', 'logo')
    op.drop_column('team', 'foundation_date')
    # ### end Alembic commands ###
