"""empty message

Revision ID: 8250e4b6decb
Revises: 648a82fe81c0
Create Date: 2023-08-26 14:25:33.413949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8250e4b6decb'
down_revision = '648a82fe81c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index(op.f('ix_position_description'), 'position', ['description'], unique=False)
    op.create_index(op.f('ix_position_name'), 'position', ['name'], unique=False)
    op.create_index(op.f('ix_position_position_id'), 'position', ['position_id'], unique=False)
    op.add_column('user', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_position_id'), 'user', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_position_id'), table_name='user')
    op.drop_column('user', 'position_id')
    op.drop_index(op.f('ix_position_position_id'), table_name='position')
    op.drop_index(op.f('ix_position_name'), table_name='position')
    op.drop_index(op.f('ix_position_description'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
